name: custom_sheet
description: Flutter package to display smart colored modal bottom sheets quickly.
version: 0.1.1+1
homepage: https://github.com/madtocc/custom_sheet

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.madtocc.custom_sheet
        pluginClass: CustomSheetPlugin
      ios:
        pluginClass: CustomSheetPlugin